const personas = [
    { nombre: "Alejandra Martínez Hidalgo", sillasPermitidas: 6 },
    { nombre: "Alejandro Afanador Mira", sillasPermitidas: 5 },
    { nombre: "Alejandro Córdoba Ospina", sillasPermitidas: 3 },
    { nombre: "Alejandro Valencia Muñoz", sillasPermitidas: 6 },
    { nombre: "Alicia Mejía Lozano", sillasPermitidas: 2 },
    { nombre: "Ana María Valencia Camelo", sillasPermitidas: 2 },
    { nombre: "Ana Sofia Arbelaez Castro", sillasPermitidas: 6 },
    { nombre: "Ana Sofia Cárdenas", sillasPermitidas: 4 },
    { nombre: "Ana Sofia Marriott", sillasPermitidas: 6 },
    { nombre: "Ana Sofia Tenorio Guzmán", sillasPermitidas: 5 },
    { nombre: "Andres Mauricio Gordillo Gomez", sillasPermitidas: 8 },
    { nombre: "Angelo Fernández Parra", sillasPermitidas: 6 },
    { nombre: "Camilo Villota Velandia", sillasPermitidas: 4 },
    { nombre: "Camilo Zapata Molina", sillasPermitidas: 4 },
    { nombre: "Carlos Manuel David Gonzalez", sillasPermitidas: 5 },
    { nombre: "Catalina Andrea Céspedes Méndez", sillasPermitidas: 6 },
    { nombre: "Catalina Villalobos Bocanegra", sillasPermitidas: 8 },
    { nombre: "Daniela González González", sillasPermitidas: 5 },
    { nombre: "Danna Valeria Sierra Mantilla", sillasPermitidas: 6 },
    { nombre: "David Francisco Ramírez Wuman", sillasPermitidas: 10 },
    { nombre: "Dulce María Alegría Mosquera", sillasPermitidas: 10 },
    { nombre: "Emmanuel Muñoz Serna", sillasPermitidas: 6 },
    { nombre: "Felipe Collazos Hoyos", sillasPermitidas: 7 },
    { nombre: "Felipe Luna Gallego", sillasPermitidas: 4 },
    { nombre: "Felipe Naranjo Escobar", sillasPermitidas: 4 },
    { nombre: "Francisco López Cárdenas", sillasPermitidas: 9 },
    { nombre: "Gabriela Márquez Rendón", sillasPermitidas: 4 },
    { nombre: "Gabriela Mora Diaz", sillasPermitidas: 8 },
    { nombre: "Gabriela Rodriguez Lopez", sillasPermitidas: 6 },
    { nombre: "Geraldine Gonzalez Mejia", sillasPermitidas: 6 },
    { nombre: "Isabel Sofía Yela Medina", sillasPermitidas: 4 },
    { nombre: "Isabella Andrade Vargas", sillasPermitidas: 3 },
    { nombre: "Isabella Bernal Hoyos", sillasPermitidas: 6 },
    { nombre: "Isabella Mantilla Echeverry", sillasPermitidas: 6 },
    { nombre: "Isabella Ruano Herrera", sillasPermitidas: 8 },
    { nombre: "Isabella Saavedra Molina", sillasPermitidas: 6 },
    { nombre: "Isabella Silva Montes", sillasPermitidas: 5 },
    { nombre: "Isabella Virginia González Rosales", sillasPermitidas: 7 },
    { nombre: "Jacobo Hidalgo Gamboa", sillasPermitidas: 5 },
    { nombre: "Jacobo Restrepo Rojas", sillasPermitidas: 9 },
    { nombre: "José Alejandro Bedoya Guzman", sillasPermitidas: 8 },
    { nombre: "José David Avendaño Herrera", sillasPermitidas: 6 },
    { nombre: "Juan Camilo Muñoz Alzate", sillasPermitidas: 10 },
    { nombre: "Juan David Amaya Serna", sillasPermitidas: 7 },
    { nombre: "Juan David Castañeda Bastidas", sillasPermitidas: 4 },
    { nombre: "Juan David Naranjo Martinez", sillasPermitidas: 3 },
    { nombre: "Juan Felipe Serrano Victoria", sillasPermitidas: 4 },
    { nombre: "Juan Francisco Villalobos Rodriguez", sillasPermitidas: 10 },
    { nombre: "Juan Guillermo Montañez Gomez", sillasPermitidas: 7 },
    { nombre: "Juan Manuel Arango Ramirez", sillasPermitidas: 3 },
    { nombre: "Juan Pablo Moncada Alvarez", sillasPermitidas: 4 },
    { nombre: "Juan Sebastián Garrido Vanegas", sillasPermitidas: 6 },
    { nombre: "Juan Sebastián Larios Valderrama", sillasPermitidas: 10 },
    { nombre: "Juanita Quintero Rico", sillasPermitidas: 7 },
    { nombre: "Laura González Torres", sillasPermitidas: 6 },
    { nombre: "Laura Maria Cáceres Alvarez", sillasPermitidas: 9 },
    { nombre: "Laura Sofia Larrarte Perdomo", sillasPermitidas: 11 },
    { nombre: "Manuel Jose Rodriguez Duran", sillasPermitidas: 6 },
    { nombre: "Mariana Ortíz Leyva", sillasPermitidas: 6 },
    { nombre: "Mariana Teresita Astaiza Rada", sillasPermitidas: 7 },
    { nombre: "Mariana Villegas López", sillasPermitidas: 8 },
    { nombre: "Maria Andrea Medina Salazar", sillasPermitidas: 8 },
    { nombre: "Maria Antonia Otero Trejos", sillasPermitidas: 6 },
    { nombre: "Maria Camila Gutierrez Estupiñan", sillasPermitidas: 5 },
    { nombre: "Maria Camila Herrera Botero", sillasPermitidas: 6 },
    { nombre: "Maria Camila Sanchez Villamarin", sillasPermitidas: 4 },
    { nombre: "Maria Isabel Martinez Jaramillo", sillasPermitidas: 11 },
    { nombre: "Maria Jose Campo Cortes", sillasPermitidas: 4 },
    { nombre: "Maria Juliana Camacho Varon", sillasPermitidas: 6 },
    { nombre: "Maria Juliana Murillo Montejo", sillasPermitidas: 11 },
    { nombre: "Maria Juliana otero trejos", sillasPermitidas: 6 },
    { nombre: "Maria Juliana Rivera Ruiz", sillasPermitidas: 6 },
    { nombre: "Maria Juliana Rico Barrero", sillasPermitidas: 10 },
    { nombre: "Maria Paula Salazar Ramirez", sillasPermitidas: 8 },
    { nombre: "Maria Sofia Tenorio Guzman", sillasPermitidas: 3 },
    { nombre: "Maria Del Mar Bedoya Bedoya", sillasPermitidas: 3 },
    { nombre: "Miguel Angel Blanco Ortega", sillasPermitidas: 10 },
    { nombre: "Natalia Gómez Benítez", sillasPermitidas: 3 },
    { nombre: "Natalia Poveda Burgos", sillasPermitidas: 4 },
    { nombre: "Nicolás Lopez Bautista", sillasPermitidas: 5 },
    { nombre: "Paulina Gómez Cortes", sillasPermitidas: 4 },
    { nombre: "Salome Haddad", sillasPermitidas: 9 },
    { nombre: "Salomé Roldán González", sillasPermitidas: 6 },
    { nombre: "Salomé Roldán González", sillasPermitidas: 6 },
    { nombre: "Salomé Roldán González", sillasPermitidas: 6 },
    { nombre: "Samantha Dussan Forero", sillasPermitidas: 5 },
    { nombre: "Samuel Gómez Hernández", sillasPermitidas: 6 },
    { nombre: "Samuel Gómez Moreno", sillasPermitidas: 6 },
    { nombre: "Samuel Lozano López", sillasPermitidas: 2 },
    { nombre: "Santiago Castaño Muñoz", sillasPermitidas: 6 },
    { nombre: "Santiago Sánchez Bedoya", sillasPermitidas: 4 },
    { nombre: "Santiago Sierra Vásquez", sillasPermitidas: 9 },
    { nombre: "Sara Hurtado Torres", sillasPermitidas: 4 },
    { nombre: "Sara Isabel Orrego Gallego", sillasPermitidas: 11 },
    { nombre: "Sara Mayor Guerrero", sillasPermitidas: 9 },
    { nombre: "Sara Montaño Dosman", sillasPermitidas: 10 },
    { nombre: "Sara Ríos", sillasPermitidas: 8 },
    { nombre: "Sara Montaño Dosman", sillasPermitidas: 10 },
    { nombre: "Sebastian Camacho Gutierrez", sillasPermitidas: 6 },
    { nombre: "Sebastián Herrera González", sillasPermitidas: 6 },
    { nombre: "Sergio Valbuena Florez", sillasPermitidas: 6 },
    { nombre: "Simón Echeverri Márquez", sillasPermitidas: 3 },
    { nombre: "Simón Gómez Quiñones", sillasPermitidas: 4 },
    { nombre: "Sofia Guerrero Soto", sillasPermitidas: 10 },
    { nombre: "Sofia Guzman Duarte", sillasPermitidas: 12 },
    { nombre: "Sofia Marmolejo Cuéllar", sillasPermitidas: 7 },
    { nombre: "Sofia Narvaez Fajardo", sillasPermitidas: 10 },
    { nombre: "Tomás Garcia", sillasPermitidas: 6 },
    { nombre: "Tomás Jaramillo", sillasPermitidas: 6 },
    { nombre: "Valentina Barriga Jama", sillasPermitidas: 6 },
    { nombre: "Valentina Méndez", sillasPermitidas: 6 },
    { nombre: "Valentina Orozco Lopez", sillasPermitidas: 7 },
    { nombre: "Valeria Nayarith Portilla Martínez", sillasPermitidas: 6 },
    { nombre: "Zara Isabella Ibarra Montenegro", sillasPermitidas: 8 }
];

export default personas;